project_id = "eozdslszmuiamycpsepe"

[functions.process-order]
verify_jwt = false

[functions.find-driver]
verify_jwt = false

[functions.reassign-driver]
verify_jwt = false

[functions.check-driver-timeout]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.create-demo-accounts]
verify_jwt = false

[functions.create-user]
verify_jwt = false
